import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container flex flex-col gap-4 mx-auto px-12">
          <div className='flex gap-4 bg-sky-100 rounded'>
            <Link href="/">Home</Link>
            <Link href="/snippets/new">New</Link>
            <Link href="/snippets/update">Update</Link>
            <Link href="/snippets/delete">Delete</Link>
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
